coverage treshold6

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -54,15 +54,14 @@ jobs:
         echo -e "${YELLOW}[ EXECUTING ] > Executing coverage analysis.${BLANK}"
         COV_RATE=$(coverage report -m --omit="${WORKING_DIR}/tests/*" --precision=2 | grep "TOTAL" | awk -F " " '{print $NF}')
         echo -e "${CYAN}[ INFO ] > Code coverage is ${COV_RATE}.${BLANK}"
-        coverage report -m --omit="${WORKING_DIR}/tests/* --precision=2
-        if [[ ${COV_RATE//%} < ${COVERAGE_THRESHOLD} ]]
-        then
-          echo -e "${RED}[ FAILURE ] > Code coverage is ${COV_RATE} below threshold ${COVERAGE_THRESHOLD}%. Tests are too weak.${BLANK}"
-          exit 1
-        else
-          echo -e "${GREEN}[ SUCCESS ] > Code coverage is ${COV_RATE} above threshold ${COVERAGE_THRESHOLD}%. Tests are ok.${BLANK}"
-        fi
-        #coverage run -m --source=. pytest ${WORKING_DIR}/tests
+        # coverage report -m --omit="${WORKING_DIR}/tests/* --precision=2
+        # if [[ ${COV_RATE//%} < ${COVERAGE_THRESHOLD} ]]
+        # then
+        #   echo -e "${RED}[ FAILURE ] > Code coverage is ${COV_RATE} below threshold ${COVERAGE_THRESHOLD}%. Tests are too weak.${BLANK}"
+        #   exit 1
+        # else
+        #   echo -e "${GREEN}[ SUCCESS ] > Code coverage is ${COV_RATE} above threshold ${COVERAGE_THRESHOLD}%. Tests are ok.${BLANK}"
+        # fi
     # - name: Code coverage with coverage
     #   id: code-coverage
     #   run: |
